defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: e_gamify_development

test: &test
  <<: *defaults
  database: e_gamify_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: e_gamify
  uri: <%= ENV['MONGODB_URI'] %>
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>

cucumber:
  <<: *test
